name: Build & Push Docker on index.html Change

on:
  push:
    branches:
      - main
    paths:
      - "index.html"   # index.html 파일이 변경될 때만 실행

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. DockerHub 로그인
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. 버전 태그 생성 (날짜+빌드번호)
      - name: Set version
        id: version
        run: echo "VERSION=$(date +'%Y%m%d')-${{ github.run_number }}" >> $GITHUB_ENV

      # 5. Docker Build & Push
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            your-dockerhub-username/your-app:latest
            your-dockerhub-username/your-app:${{ env.VERSION }}
